name: daily-test

on:
  schedule:
  - cron: '0 10 * * *'

jobs:

  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.12']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - uses: clonedSemicolon/setup-strace@v13
    - name: Build the LogonTracer Docker Image and start
      run: |
        docker image build ./docker -t jpcertcc/docker-logontracer:latest
        docker container run --detach --publish=7474:7474 --publish=7687:7687  --publish=8080:8080 -e LTHOSTNAME=localhost jpcertcc/docker-logontracer
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cython
        pip install numpy
        pip install scipy
        pip install statsmodels
        pip install -r requirements.txt
    - name: List installed Python packages
      run: pip list
    - name: Test for LogonTracer web gui
      run: curl --verbose --show-error http://localhost:8080
    - name: Test for LogonTracer log import
      run: python logontracer.py -e sample/Security.evtx
    - name: Upload strace artifacts
      uses: actions/upload-artifact@v4
      with:
        name: strace-logs-${{ github.job }}-${{ matrix.flavor || 'lint' }}-${{ github.run_id }}-${{ github.run_attempt }}-${{ strategy.job-index || 0 }}
        path: /home/runner/strace_logs/
